config/routes.rb
RubyTraining::Application.routes.draw do

  root :to => 'curriculums#index'
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  resources :user_sessions
  resources :users
  resources :curriculums do
    resources :exam_answers
    resources :exam_questions do
      resources :exam_answers
    end
  end
  namespace :admin do
    root :to => 'menu#index'
    resources :curriculums do
      resources :exam_questions
    end
    resources :users do
      resources :exam_status
    end
  end
  

end

app/models/curriculum.rb
# -*- coding: utf-8 -*-
class Curriculum < ActiveRecord::Base
  has_attached_file :textbook

  has_many :exam_questions
  has_many :exam_answers, :through => :exam_questions

  def questions_count
    exam_questions.count
  end

  def answers_count(user_id = nil)
    answers = if user_id
      exam_answers.where(:user_id => user_id)
    else
      exam_answers
    end
    answers.count
  end

  def finished?(user_id)
    questions_count <= answers_count(user_id)
  end

  def unfinished?(user_id)
    !finished?(user_id)
  end
end

app/controllers/admin/curriculums_controller.rb
# -*- coding: utf-8 -*-
class Admin::CurriculumsController < AdminController
  def index
    @curriculums = Curriculum.order(:sort_order)
  end

  def show
    @curriculum = Curriculum.find(params[:id])
  end

  def new
    @curriculum = Curriculum.new
  end

  def edit
    @curriculum = Curriculum.find(params[:id])
  end

  def create
    @curriculum = Curriculum.new(params[:curriculum])
    if @curriculum.save
      render :success
    else
      render :failed
    end
  end

  def update
    @curriculum = Curriculum.find(params[:id])
    if @curriculum.update_attributes(params[:curriculum])
      render :success
    else
      render :failed
    end
  end

  def destroy
    @curriculum = Curriculum.find(params[:id])
    @curriculum.destroy
  end
end

app/controllers/curriculums_controller.rb
# -*- coding: utf-8 -*-
class CurriculumsController < ApplicationController
  def index
    @curriculums = Curriculum.order(:sort_order)
  end

  def show
    @curriculum = Curriculum.find(params[:id])
  end

  def new
    @curriculum = Curriculum.new
  end

  def edit
    @curriculum = Curriculum.find(params[:id])
  end

  def create
    @curriculum = Curriculum.new(params[:curriculum])
    if @curriculum.save
      redirect_to(@curriculum, :notice => 'Curriculum was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @curriculum = Curriculum.find(params[:id])
    if @curriculum.update_attributes(params[:curriculum])
      redirect_to(@curriculum, :notice => 'Curriculum was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @curriculum = Curriculum.find(params[:id])
    @curriculum.destroy
    redirect_to(curriculums_url)
  end
end

app/helpers/curriculums_helper.rb
# -*- coding: utf-8 -*-
module CurriculumsHelper
end

app/views/admin/curriculums/_curriculum.html.erb
<tr>
  <td><%= curriculum.name %></td>
  <td><%= curriculum.description %></td>
  <td><%= curriculum.sort_order %></td>
  <td><%= link_to curriculum.textbook.original_filename, curriculum.textbook.url %></td>
  <td><%= link_to '試験設定', admin_curriculum_exam_questions_path(curriculum) %></td>
  <td><%= link_to '閲覧', [:admin, curriculum], :remote => true %></td>
  <td><%= link_to '編集', edit_admin_curriculum_path(curriculum), :remote => true %></td>
  <td><%= link_to '削除', [:admin, curriculum], :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

app/views/admin/curriculums/_form.html.erb
<%= form_for([:admin, @curriculum], :html => {:multipart => true}) do |f| %>
  <% if @curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
      <% @curriculum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "カリキュラム" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, "説明" %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :sort_order, "並び順" %><br />
    <%= f.text_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :textbook, "テキスト" %>
    <%= f.file_field :textbook %>
  </div>
<% end %>

app/views/admin/curriculums/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @curriculum.name %>
</p>

<p>
  <b>Description:</b>
  <%= @curriculum.description %>
</p>

<p>
  <b>Sort order:</b>
  <%= @curriculum.sort_order %>
</p>

<p>
  <b>Textbook:</b>
  <%= link_to @curriculum.textbook.original_filename, @curriculum.textbook.url %>
</p>

app/views/admin/curriculums/destroy.js.erb
$.notifyDialog('削除しました', {title: '削除'});
$.getScript('<%= admin_curriculums_url %>');

app/views/admin/curriculums/edit.js.erb
$.formDialog('<%= escape_javascript(render(:partial => "form")) %>', {title: '編集'});

app/views/admin/curriculums/failed.js.erb
$.notifyDialog('<%= raw @curriculum.errors.full_messages.join("<br />") %>', {title: '失敗'});

app/views/admin/curriculums/index.html.erb
<% content_for :title do %>
  カリキュラム管理
<% end %>

<table>
  <thead>
    <tr>
      <th>カリキュラム</th>
      <th>説明</th>
      <th>並び順</th>
      <th>テキスト</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @curriculums %>
  </tbody>
</table>

<br />

<%= link_to '新規カリキュラム作成', new_admin_curriculum_path, :remote => true %> |
<%= link_to 'メニューに戻る', admin_root_path %>

app/views/admin/curriculums/index.js.erb
$('tbody').html('<%= escape_javascript(render(@curriculums)) %>');

app/views/admin/curriculums/new.js.erb
$.formDialog('<%= escape_javascript(render(:partial => "form")) %>', {title: '新規作成'});

app/views/admin/curriculums/show.js.erb
$.notifyDialog('<%= escape_javascript(render(:partial => "show")) %>', {title: '詳細表示'});

app/views/admin/curriculums/success.js.erb
$.notifyDialog('保存しました', {title: '成功'});
$.getScript('<%= admin_curriculums_url %>');