config/routes.rb
RubyTraining::Application.routes.draw do

  root :to => 'curriculums#index'
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  resources :user_sessions
  resources :users
  resources :curriculums do
    resources :exam_answers
    resources :exam_questions do
      resources :exam_answers
    end
  end
  namespace :admin do
    root :to => 'menu#index'
    resources :curriculums do
      resources :exam_questions
    end
    resources :users do
      resources :exam_status
    end
  end
  

end

app/models/exam_answer.rb
# -*- coding: utf-8 -*-
class ExamAnswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :exam_question

  def self.answered(user_id, curriculum_id)
    where(:user_id => user_id).includes(:exam_question) & ExamQuestion.where(:curriculum_id => curriculum_id)
  end
end

app/controllers/exam_answers_controller.rb
# -*- coding: utf-8 -*-
class ExamAnswersController < ApplicationController
  before_filter :load_curriculum, :load_exam_question

  def index
    @questions = @curriculum.exam_questions
    @answers = @curriculum.exam_answers.where(:user_id => current_user.id).index_by(&:exam_question_id)
  end

  def show
    @exam_answer = ExamAnswer.find(params[:id])
  end

  def new
    @exam_answer = ExamAnswer.new
  end

  def edit
    @exam_answer = ExamAnswer.find(params[:id])
  end

  def create
    @exam_answer = @exam_question.exam_answers.new(params[:exam_answer])
    @exam_answer.user_id = current_user.id
    if @exam_answer.save
      next_question = @curriculum.exam_questions.where("number > ?", @exam_question.number).order(:number).first
      if next_question
        redirect_to new_curriculum_exam_question_exam_answer_path(@curriculum, next_question)
      else
        render 'finished'
      end
    else
      render :action => "new"
    end
  end

  def update
    @exam_answer = ExamAnswer.find(params[:id])

    respond_to do |format|
      if @exam_answer.update_attributes(params[:exam_answer])
        format.html { redirect_to(@exam_answer, :notice => 'Exam answer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exam_answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @exam_answer = ExamAnswer.find(params[:id])
    @exam_answer.destroy

    respond_to do |format|
      format.html { redirect_to(exam_answers_url) }
      format.xml  { head :ok }
    end
  end

  private

  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id])
  end

  def load_exam_question
    @exam_question = ExamQuestion.find(params[:exam_question_id]) if params[:exam_question_id]
  end
end

app/helpers/exam_answers_helper.rb
# -*- coding: utf-8 -*-
module ExamAnswersHelper
end

app/views/exam_answers/_form.html.erb
<%= form_for([@curriculum, @exam_question, @exam_answer]) do |f| %>
  <% if @exam_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam_answer.errors.count, "error") %> prohibited this exam_answer from being saved:</h2>

      <ul>
      <% @exam_answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  設問:<br />
  <%= @exam_question.question %><br /><br />
  <div class="field">
    <%= f.label :answer, "解答:" %><br />
    <%= f.text_area :answer %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exam_answers/edit.html.erb
<h1>Editing exam_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam_answer %> |
<%= link_to 'Back', exam_answers_path %>

app/views/exam_answers/finished.html.erb
<% content_for :title do %>
  <%= @curriculum.name %>
<% end %>

<p>
  Examination Finished.
</p>

<%= link_to 'Back', root_path %>

app/views/exam_answers/index.html.erb
<% content_for :title do %>
  <%= @curriculum.name %>/採点結果
<% end %>

<table>
  <thead>
    <tr>
      <th>設問</th>
      <th>解答例</th>
      <th>解答</th>
      <th>得点</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
	<td><%= question.question %></td>
	<td><%= question.answer %></td>
	<td><%= @answers[question.id] && @answers[question.id].answer %></td>
	<td>
	  <%= @answers[question.id] && @answers[question.id].score %> /
	  <%= question.score %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to '戻る', curriculum_path(@curriculum) %>

app/views/exam_answers/new.html.erb
<% content_for :title do %>
  <%= @curriculum.name %>
<% end %>

<%= render 'form' %>

app/views/exam_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @exam_answer.user %>
</p>

<p>
  <b>Exam question:</b>
  <%= @exam_answer.exam_question %>
</p>

<p>
  <b>Answer:</b>
  <%= @exam_answer.answer %>
</p>

<p>
  <b>Score:</b>
  <%= @exam_answer.score %>
</p>


<%= link_to 'Edit', edit_exam_answer_path(@exam_answer) %> |
<%= link_to 'Back', exam_answers_path %>