config/routes.rb
RubyTraining::Application.routes.draw do

  root :to => 'curriculums#index'
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  resources :user_sessions
  resources :users
  resources :curriculums do
    resources :exam_answers
    resources :exam_questions do
      resources :exam_answers
    end
  end
  namespace :admin do
    root :to => 'menu#index'
    resources :curriculums do
      resources :exam_questions
    end
    resources :users do
      resources :exam_status
    end
  end
  

end

app/models/exam_question.rb
# -*- coding: utf-8 -*-
class ExamQuestion < ActiveRecord::Base
  belongs_to :curriculum
  has_many :exam_answers
end

app/controllers/admin/exam_questions_controller.rb
# -*- coding: utf-8 -*-
class Admin::ExamQuestionsController < AdminController
  before_filter :load_curriculum

  def index
    @exam_questions = @curriculum.exam_questions
  end

  def show
    @exam_question = @curriculum.exam_questions.find(params[:id])
  end

  def new
    @exam_question = @curriculum.exam_questions.new()
  end

  def edit
    @exam_question = @curriculum.exam_questions.find(params[:id])
  end

  def create
    @exam_question = @curriculum.exam_questions.new(params[:exam_question])
    if @exam_question.save
      redirect_to([:admin, @curriculum, @exam_question], :notice => 'Exam question was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @exam_question = @curriculum.exam_questions.find(params[:id])
    if @exam_question.update_attributes(params[:exam_question])
      redirect_to([:admin, @curriculum, @exam_question], :notice => 'Exam question was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @exam_question = @curriculum.exam_questions.find(params[:id])
    @exam_question.destroy
    redirect_to(admin_curriculum_exam_questions_url)
  end

  private

  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id])
  end
end

app/controllers/exam_questions_controller.rb
# -*- coding: utf-8 -*-
class ExamQuestionsController < ApplicationController
  before_filter :load_curriculum
  
  def index
    redirect_to new_curriculum_exam_question_exam_answer_path(@curriculum, @curriculum.exam_questions.order(:number).first)
  end

  def show
    @exam_question = @curriculum.exam_questions.find(params[:id])
  end

  # GET /exam_questions/new
  # GET /exam_questions/new.xml
  def new
    @exam_question = ExamQuestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @exam_question }
    end
  end

  # GET /exam_questions/1/edit
  def edit
    @exam_question = ExamQuestion.find(params[:id])
  end

  # POST /exam_questions
  # POST /exam_questions.xml
  def create
    @exam_question = ExamQuestion.new(params[:exam_question])

    respond_to do |format|
      if @exam_question.save
        format.html { redirect_to(@exam_question, :notice => 'Exam question was successfully created.') }
        format.xml  { render :xml => @exam_question, :status => :created, :location => @exam_question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @exam_question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /exam_questions/1
  # PUT /exam_questions/1.xml
  def update
    @exam_question = ExamQuestion.find(params[:id])

    respond_to do |format|
      if @exam_question.update_attributes(params[:exam_question])
        format.html { redirect_to(@exam_question, :notice => 'Exam question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exam_question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exam_questions/1
  # DELETE /exam_questions/1.xml
  def destroy
    @exam_question = ExamQuestion.find(params[:id])
    @exam_question.destroy

    respond_to do |format|
      format.html { redirect_to(exam_questions_url) }
      format.xml  { head :ok }
    end
  end
  
  private

  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id])
  end
end

app/helpers/exam_questions_helper.rb
# -*- coding: utf-8 -*-
module ExamQuestionsHelper
end

app/views/exam_questions/_form.html.erb
<%= form_for(@exam_question) do |f| %>
  <% if @exam_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam_question.errors.count, "error") %> prohibited this exam_question from being saved:</h2>

      <ul>
      <% @exam_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exam_questions/edit.html.erb
<h1>Editing exam_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam_question %> |
<%= link_to 'Back', exam_questions_path %>

app/views/exam_questions/index.html.erb
<h1>Listing exam_questions</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exam_questions.each do |exam_question| %>
  <tr>
    <td><%= exam_question.question %></td>
    <td><%= exam_question.answer %></td>
    <td><%= link_to 'Show', exam_question %></td>
    <td><%= link_to 'Edit', edit_exam_question_path(exam_question) %></td>
    <td><%= link_to 'Destroy', exam_question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exam question', new_exam_question_path %>

app/views/exam_questions/new.html.erb
<h1>New exam_question</h1>

<%= render 'form' %>

<%= link_to 'Back', exam_questions_path %>

app/views/exam_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @exam_question.question %>
</p>

<p>
  <%= label_tag :answer %>
  <%= text_field_tag :answer %>
</p>

<%= link_to 'Next', curriculum_exam_question_path