config/routes.rb
RubyTraining::Application.routes.draw do

  root :to => 'curriculums#index'
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  resources :user_sessions
  resources :users
  resources :curriculums do
    resources :exam_answers
    resources :exam_questions do
      resources :exam_answers
    end
  end
  namespace :admin do
    root :to => 'menu#index'
    resources :curriculums do
      resources :exam_questions
    end
    resources :users do
      resources :exam_status
    end
  end
  

end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :exam_answers

  def admin?
    admin_flag
  end
end

app/controllers/admin/users_controller.rb
# -*- coding: utf-8 -*-
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      render :success
    else
      render :failed
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      render :success
    else
      render :failed
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      render :success
    else
      render :failed
    end
  end
end

app/helpers/users_helper.rb
# -*- coding: utf-8 -*-
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin_flag %><br />
    <%= f.check_box :admin_flag %>
  </div>
<% end %>

app/views/admin/users/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Login:</b>
  <%= @user.login %>
</p>

<p>
  <b>Login count:</b>
  <%= @user.login_count %>
</p>

<p>
  <b>Current login at:</b>
  <%= @user.current_login_at && l(@user.current_login_at) %>
</p>

<p>
  <b>Last login at:</b>
  <%= @user.current_login_at && l(@user.last_login_at) %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.admin_flag ? "*" : "" %>
</p>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.login %></td>
  <td><%= user.login_count %></td>
  <td><%= user.current_login_at && l(user.current_login_at) %></td>
  <td><%= user.last_login_at && l(user.last_login_at) %></td>
  <td><%= user.admin_flag ? "*" : "" %></td>
  <td><%= link_to '試験管理', admin_user_exam_status_path(user) %></td>
  <td><%= link_to '閲覧', [:admin, user], :remote => true %></td>
  <td><%= link_to '編集', edit_admin_user_path(user), :remote => true %></td>
  <td><%= link_to '削除', [:admin, user], :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

app/views/admin/users/destroy.js.erb
$.notifyDialog('削除しました', {title: '削除'});
$.getScript('<%= admin_users_url %>');

app/views/admin/users/edit.js.erb
$.formDialog('<%= escape_javascript(render(:partial => "form")) %>', {title: '編集'});

app/views/admin/users/failed.js.erb
$.notifyDialog('<%= raw @user.errors.full_messages.join("<br />") %>', {title: '失敗'});

app/views/admin/users/index.html.erb
<% content_for :title do %>
  ユーザ管理
<% end %>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name :login %></th>
      <th><%= User.human_attribute_name :login_count %></th>
      <th><%= User.human_attribute_name :current_login_at %></th>
      <th><%= User.human_attribute_name :last_login_at %></th>
      <th><%= User.human_attribute_name :admin_flag %></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

<br />

<%= link_to '新規ユーザ作成', new_admin_user_path, :remote => true %> |
<%= link_to 'メニューに戻る', admin_root_path %>

app/views/admin/users/index.js.erb
$('tbody').html('<%= escape_javascript(render(@users)) %>');

app/views/admin/users/new.js.erb
$.formDialog('<%= escape_javascript(render(:partial => "form")) %>', {title: '新規作成'});

app/views/admin/users/show.js.erb
$.notifyDialog('<%= escape_javascript(render(:partial => "show")) %>', {title: '詳細表示'});

app/views/admin/users/success.js.erb
$.notifyDialog('保存しました', {title: '成功'});
$.getScript('<%= admin_users_url %>');